### ISSUE TITLE
Incompatible change required to Flow Router

### ISSUE THREAD

**Issue by craigdrayton** [t3db0t/meteor-accounts-invite#1]
HI,

This package is just what I need, thanks! I'm getting this error on attempting to add it to Meteor:

```
error: Potentially incompatible change required to top-level dependency: kadira:flow-router 2.10.1, was 2.12.1.
Constraints on package "kadira:flow-router":
* kadira:flow-router@2.10.1 <- useraccounts:flow-routing 1.14.2
* kadira:flow-router@=2.10.1 || =2.9.0 || =2.8.0 || =2.7.0 || =2.6.2 || =2.5.0 <- brettle:accounts-patch-ui 0.1.12 <- t3db0t:accounts-invite 1.2.0
```

**Comment by t3db0t** [comment]
Hm, looks like `brettle:accounts-patch-ui` relies on some undocumented features of `useraccounts:flow-routing`:
https://github.com/brettle/meteor-accounts-patch-ui/blob/master/package.js#L64

You might have to open a ticket on `brettle:accounts-patch-ui` to see if the version can be increased :/
