### ISSUE TITLE
Dependency Issues

### ISSUE THREAD

**Issue by louieBuera** [t3db0t/meteor-accounts-invite#3]
Hi! This looks perfect for my app, but I haven't been able to try it since I've been having errors trying to add it:

   While selecting package versions:
   error: Conflict: Constraint blaze@=2.1.5 || =2.1.4 || =2.1.3 || =2.1.2
   || =2.1.1 || =2.1.0 || =2.1.6 || =2.1.7 is not satisfied by blaze
   2.1.8.
   Constraints on package "blaze":
- blaze@=2.1.8 <- top level
- blaze@2.1.8 <- spacebars 1.0.12 <- blaze-html-templates 1.0.4
- blaze@2.1.7 <- ui 1.0.11 <- aldeed:autoform 5.8.1
- blaze@2.1.8 <- launch-screen 1.0.12 <- mobile-experience 1.0.4
- blaze@2.1.7 <- blaze-html-templates 1.0.4
- blaze@2.1.8 <- templating 1.1.12 <- accounts-ui-unstyled 1.1.12 <-
  accounts-ui 1.1.9
- blaze@2.1.8 <- templating 1.1.12 <- aldeed:autoform 5.8.1
- blaze@2.0.3 <- kadira:blaze-layout 2.3.0
- blaze@2.1.8 <- accounts-base 1.2.8 <- accounts-password 1.1.11
- blaze@2.1.3 <- alanning:roles 1.2.15
- blaze@=2.1.5 || =2.1.4 || =2.1.3 || =2.1.2 || =2.1.1 || =2.1.0 ||
  =2.1.6 || =2.1.7 <- brettle:accounts-patch-ui 0.1.12 <-
  t3db0t:accounts-invite 1.2.0
- blaze@2.0.1 || 2.0.2 || 2.0.3 <- aldeed:autoform 5.8.1

Some help would be greatly appreciated.

**Comment by t3db0t** [comment]
Howdy! The owner of `brettle:accounts-patch-ui` JUST updated with support for Blaze 2.1.8, so `meteor update` again should clear everything up.
